services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Gitlab\Client\HttpClientFactory: ~

    App\Gitlab\Serializer\:
        resource: '%kernel.project_dir%/src/Gitlab/Serializer'

    gitlab.http_client.auto_config:
        class: 'Symfony\Component\HttpClient\ScopingHttpClient'
        decorates: 'gitlab.client'
        decoration_inner_name: 'gitlab.http_client.inner'
        factory: ['@App\Gitlab\Client\HttpClientFactory', 'create']
        lazy: true
        arguments:
            $client: '@gitlab.http_client.inner'

    App\Gitlab\Client\MergeRequest\QueryHandler\:
        resource: '%kernel.project_dir%/src/Gitlab/Client/MergeRequest/QueryHandler/**/*Handler.php'
        autoconfigure: false
        tags:
            - { name: 'messenger.message_handler', bus: 'query.bus' }

#    App\Gitlab\Client\MergeRequest\CommandHandler\:
#        resource: '%kernel.project_dir%/src/Gitlab/Client/MergeRequest/CommandHandler/**/*Handler.php'
#        autoconfigure: false
#        tags:
#            - { name: 'messenger.message_handler', bus: 'command.bus' }

    App\Gitlab\Config\FilesystemLoader:
        arguments:
            $configDirectory: '%kernel.project_dir%/user-config'
            $metrics: !tagged_locator { tag: 'metrics.gitlab', default_index_method: 'supportedMetric' }

    App\Gitlab\Config\ConfigContext: ~

    App\Gitlab\Config\Config:
        class: 'App\Gitlab\Config\Config'
        factory: ['@App\Gitlab\Config\FilesystemLoader', 'load']
