services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Infrastructure\Doctrine\DataFixtures\:
        resource: '%kernel.project_dir%/src/Infrastructure/Doctrine/DataFixtures'

    App\Infrastructure\Doctrine\DataFixtures\ConfigFixtures:
        arguments:
            $configDirectory: '%kernel.project_dir%/user-config'
